"""align odds model with transformer

Revision ID: 64de8147bd69
Revises: fd1defd61b1d
Create Date: 2026-09-05 22:55:28.042713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64de8147bd69'
down_revision: Union[str, Sequence[str], None] = 'fd1defd61b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odds', sa.Column('source', sa.String(length=100), nullable=False))
    op.add_column('odds', sa.Column('phase', sa.String(length=20), nullable=False))
    op.drop_column('odds', 'snapshot')
    op.drop_column('odds', 'source_name')
    op.drop_column('odds', 'source_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odds', sa.Column('source_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('odds', sa.Column('source_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('odds', sa.Column('snapshot', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('odds', 'phase')
    op.drop_column('odds', 'source')
    # ### end Alembic commands ###
