"""create initial schema

Revision ID: fd1defd61b1d
Revises: 
Create Date: 2026-08-16 22:10:38.111405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd1defd61b1d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('referees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('referee_id', sa.Integer(), nullable=True),
    sa.Column('match_date', sa.Date(), nullable=False),
    sa.Column('kickoff_time', sa.Time(), nullable=True),
    sa.Column('home_goals', sa.SmallInteger(), nullable=False),
    sa.Column('away_goals', sa.SmallInteger(), nullable=False),
    sa.Column('result', sa.String(length=1), nullable=False),
    sa.Column('home_half_time_goals', sa.SmallInteger(), nullable=True),
    sa.Column('away_half_time_goals', sa.SmallInteger(), nullable=True),
    sa.Column('half_time_result', sa.String(length=1), nullable=True),
    sa.CheckConstraint("result IN ('H', 'D', 'A')", name='chk_result'),
    sa.CheckConstraint('home_goals >= 0 AND away_goals >= 0', name='chk_goals_non_negative'),
    sa.CheckConstraint('home_team_id <> away_team_id', name='chk_different_teams'),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['referee_id'], ['referees.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_statistics',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('home_shots', sa.SmallInteger(), nullable=True),
    sa.Column('away_shots', sa.SmallInteger(), nullable=True),
    sa.Column('home_shots_on_target', sa.SmallInteger(), nullable=True),
    sa.Column('away_shots_on_target', sa.SmallInteger(), nullable=True),
    sa.Column('home_fouls', sa.SmallInteger(), nullable=True),
    sa.Column('away_fouls', sa.SmallInteger(), nullable=True),
    sa.Column('home_corners', sa.SmallInteger(), nullable=True),
    sa.Column('away_corners', sa.SmallInteger(), nullable=True),
    sa.Column('home_yellow_cards', sa.SmallInteger(), nullable=True),
    sa.Column('away_yellow_cards', sa.SmallInteger(), nullable=True),
    sa.Column('home_red_cards', sa.SmallInteger(), nullable=True),
    sa.Column('away_red_cards', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('odds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=30), nullable=False),
    sa.Column('selection', sa.String(length=20), nullable=False),
    sa.Column('line', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('snapshot', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('odds')
    op.drop_table('match_statistics')
    op.drop_table('matches')
    op.drop_table('teams')
    op.drop_table('seasons')
    op.drop_table('referees')
    op.drop_table('bookmakers')
    # ### end Alembic commands ###
